# Generated by Django 4.1 on 2022-09-28 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ForoNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado')], default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creado'],
            },
        ),
        migrations.DeleteModel(
            name='Discusion',
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
    ]
