# Generated by Django 4.1 on 2022-09-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForoNews', '0002_post_delete_discusion_delete_foro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
