# Generated by Django 4.1.1 on 2022-09-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=30, verbose_name='Direccion del estadio')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre oficial del estadio')),
            ],
        ),
        migrations.CreateModel(
            name='FechaGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipolocal', models.CharField(max_length=25)),
                ('equipovisita', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField()),
                ('resultado', models.CharField(max_length=25)),
                ('estadio', models.CharField(max_length=30, verbose_name='Nombre oficial del estadio')),
            ],
        ),
        migrations.CreateModel(
            name='FechaPlayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipolocal', models.CharField(max_length=25)),
                ('equipovisita', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(max_length=25)),
                ('estadio', models.CharField(max_length=30, null=True, verbose_name='Nombre oficial del estadio')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre completo del jugador')),
                ('equipo', models.CharField(max_length=50, verbose_name='Pais en el que juega')),
                ('posicion', models.CharField(max_length=25, verbose_name='Posicion en la que juega')),
                ('sancionado', models.BooleanField()),
                ('lesionado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1, verbose_name='Nombre del grupo')),
                ('instanciaplayoff', models.CharField(max_length=25)),
                ('jugadores', models.CharField(max_length=25)),
            ],
        ),
    ]
